using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

namespace SteeringBehaviours
{
    public class AIAgent : MonoBehaviour
    {
      
        public float maxSpeed = 10f;
        public float maxDistance = 5f;
        public bool updatePosition = true;
        public bool updateRotation = true;
        public Vector3 velocity;

        private Vector3 force;
        private SteeringBehaviour[] behaviours;
        private NavMeshAgent agent;
        private void Awake()
        {
            behaviours = GetComponents<SteeringBehaviour>();
            agent = GetComponent<NavMeshAgent>();
        }

        // Update is called once per frame
        void Update()
        {

            ComputeForces();
            ApplyVelocity();
        }

        // calculate all the forces generated by each attached steeringbehaviour
        private void ComputeForces()
        {
            //Rest Velocity
            velocity = Vector3.zero;
            //loop through each behaviour
            for (int i = 0; i < behaviours.Length; i++)
            {
                // get force from behaviour 
                Vector3 force = behaviours[i].GetForce();
                //add it to velocity
                velocity += force;
            }
        }

        //apply the total velocity to the AIAgent
        private void ApplyVelocity()
        {
            //get an offset position as new target
            Vector3 point = transform.position + velocity * Time.deltaTime;
            //Apply velocity to transform
            agent.SetDestination(point);
        }
    }
}